DROP TABLE `ab_test_results`;--> statement-breakpoint
DROP TABLE `abandoned_carts`;--> statement-breakpoint
DROP TABLE `analytics`;--> statement-breakpoint
DROP TABLE `appointments`;--> statement-breakpoint
DROP TABLE `automation_rules`;--> statement-breakpoint
DROP TABLE `booking_reviews`;--> statement-breakpoint
DROP TABLE `booking_time_slots`;--> statement-breakpoint
DROP TABLE `bookings`;--> statement-breakpoint
DROP TABLE `bot_settings`;--> statement-breakpoint
DROP TABLE `business_templates`;--> statement-breakpoint
DROP TABLE `campaignLogs`;--> statement-breakpoint
DROP TABLE `campaigns`;--> statement-breakpoint
DROP TABLE `conversations`;--> statement-breakpoint
DROP TABLE `customer_reviews`;--> statement-breakpoint
DROP TABLE `discount_codes`;--> statement-breakpoint
DROP TABLE `email_verification_tokens`;--> statement-breakpoint
DROP TABLE `google_integrations`;--> statement-breakpoint
DROP TABLE `google_oauth_settings`;--> statement-breakpoint
DROP TABLE `invoices`;--> statement-breakpoint
DROP TABLE `keyword_analysis`;--> statement-breakpoint
DROP TABLE `limited_time_offers`;--> statement-breakpoint
DROP TABLE `loyalty_points`;--> statement-breakpoint
DROP TABLE `loyalty_redemptions`;--> statement-breakpoint
DROP TABLE `loyalty_rewards`;--> statement-breakpoint
DROP TABLE `loyalty_settings`;--> statement-breakpoint
DROP TABLE `loyalty_tiers`;--> statement-breakpoint
DROP TABLE `loyalty_transactions`;--> statement-breakpoint
DROP TABLE `merchants`;--> statement-breakpoint
DROP TABLE `messages`;--> statement-breakpoint
DROP TABLE `notification_templates`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `occasion_campaigns`;--> statement-breakpoint
DROP TABLE `order_notifications`;--> statement-breakpoint
DROP TABLE `order_payments`;--> statement-breakpoint
DROP TABLE `order_tracking_logs`;--> statement-breakpoint
DROP TABLE `orders`;--> statement-breakpoint
DROP TABLE `password_reset_attempts`;--> statement-breakpoint
DROP TABLE `password_reset_tokens`;--> statement-breakpoint
DROP TABLE `payment_gateways`;--> statement-breakpoint
DROP TABLE `payment_links`;--> statement-breakpoint
DROP TABLE `payment_refunds`;--> statement-breakpoint
DROP TABLE `payments`;--> statement-breakpoint
DROP TABLE `planChangeLogs`;--> statement-breakpoint
DROP TABLE `plans`;--> statement-breakpoint
DROP TABLE `products`;--> statement-breakpoint
DROP TABLE `quick_responses`;--> statement-breakpoint
DROP TABLE `referral_codes`;--> statement-breakpoint
DROP TABLE `referrals`;--> statement-breakpoint
DROP TABLE `rewards`;--> statement-breakpoint
DROP TABLE `salla_connections`;--> statement-breakpoint
DROP TABLE `sari_personality_settings`;--> statement-breakpoint
DROP TABLE `scheduled_messages`;--> statement-breakpoint
DROP TABLE `sentiment_analysis`;--> statement-breakpoint
DROP TABLE `seo_analytics`;--> statement-breakpoint
DROP TABLE `seo_backlinks`;--> statement-breakpoint
DROP TABLE `seo_keywords_analysis`;--> statement-breakpoint
DROP TABLE `seo_meta_tags`;--> statement-breakpoint
DROP TABLE `seo_open_graph`;--> statement-breakpoint
DROP TABLE `seo_pages`;--> statement-breakpoint
DROP TABLE `seo_performance_alerts`;--> statement-breakpoint
DROP TABLE `seo_recommendations`;--> statement-breakpoint
DROP TABLE `seo_sitemaps`;--> statement-breakpoint
DROP TABLE `seo_structured_data`;--> statement-breakpoint
DROP TABLE `seo_tracking_codes`;--> statement-breakpoint
DROP TABLE `seo_twitter_cards`;--> statement-breakpoint
DROP TABLE `service_categories`;--> statement-breakpoint
DROP TABLE `service_packages`;--> statement-breakpoint
DROP TABLE `service_reviews`;--> statement-breakpoint
DROP TABLE `services`;--> statement-breakpoint
DROP TABLE `setup_wizard_progress`;--> statement-breakpoint
DROP TABLE `signup_prompt_test_results`;--> statement-breakpoint
DROP TABLE `signup_prompt_variants`;--> statement-breakpoint
DROP TABLE `staff_members`;--> statement-breakpoint
DROP TABLE `subscriptions`;--> statement-breakpoint
DROP TABLE `supportTickets`;--> statement-breakpoint
DROP TABLE `sync_logs`;--> statement-breakpoint
DROP TABLE `testConversations`;--> statement-breakpoint
DROP TABLE `testDeals`;--> statement-breakpoint
DROP TABLE `testMessages`;--> statement-breakpoint
DROP TABLE `testMetricsDaily`;--> statement-breakpoint
DROP TABLE `trySariAnalytics`;--> statement-breakpoint
DROP TABLE `weekly_sentiment_reports`;--> statement-breakpoint
DROP TABLE `whatsapp_connection_requests`;--> statement-breakpoint
DROP TABLE `whatsappConnections`;--> statement-breakpoint
DROP TABLE `whatsapp_instances`;--> statement-breakpoint
DROP TABLE `whatsapp_requests`;--> statement-breakpoint
DROP INDEX `users_openId_unique` ON `users`;--> statement-breakpoint
ALTER TABLE `users` ADD PRIMARY KEY(`id`);--> statement-breakpoint
ALTER TABLE `users` ADD CONSTRAINT `users_openId_unique` UNIQUE(`openId`);--> statement-breakpoint
ALTER TABLE `users` DROP COLUMN `password`;